# Tendermint KMS configuration file

## Chain Configuration

### Iris Hub Network

[[chain]]
id = "irishub"
key_format = { type = "bech32", account_key_prefix = "iap", consensus_key_prefix = "icp" }
state_file = "/home/tmkms/state/irishub-consensus.json"

## Signing Provider Configuration

### Ledger Provider Configuration

[[providers.ledgertm]]
chain_ids = ["cosmoshub-1"]

## Validator Configuration

[[validator]]
chain_id = "irishub"
addr = "tcp://deadbeefdeadbeefdeadbeefdeadbeefdeadbeef@example1.example.com:26658"
secret_key = "/home/tmkms/secrets/kms-identity.key"
protocol_version = "legacy"
reconnect = true
