[[chain]]
id = "gravity-testnet"
key_format = { type = "bech32", account_key_prefix = "cosmospub", consensus_key_prefix = "cosmosvalconspub" }
[[validator]]
addr = "tcp://gravity:61278"
chain_id = "gravity-testnet"
reconnect = true # true is the default
secret_key = "/home/tmkms/secrets/kms-identity.key"
protocol_version = "legacy"
[[providers.softsign]]
chain_ids = ["gravity-testnet"]
path = "/home/tmkms/secrets/signing.key"