version: '3'

services:
  gravity:
    build:
      context: ./gravity
      dockerfile: ./Dockerfile
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 61278:61278
    volumes:
      #  volume for test script
      - ./gravity:/root/~
    command: tm-signer-harness run --tmhome="/root/.gravity" -addr tcp://0.0.0.0:61278 -accept-retries 1000000

  tmkms:
    build:
      context: ./tmkms
      dockerfile: ./Dockerfile
    command: tmkms start -v