version: '3'

services:
  gravity:
    build:
      context: ./gravity
      dockerfile: ./Dockerfile
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
    volumes:
      - ./gravity:/root/~
    command: gravity start

  tmkms:
    build:
      context: ./tmkms
      dockerfile: ./Dockerfile