version: '3'

services:
  gravity:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - .:/root/~
    command: gravity start